import { SignOutButton, SignUpButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { useState } from "react";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>{user.isSignedIn ? <SignOutButton /> : <SignUpButton />}</nav>
      <main>{user.isSignedIn ? <LoginContent /> : <NotLoginContent />}</main>
    </>
  );
}

const LoginContent = () => {
  const user = useUser();

  const posts = api.post.getALl.useQuery();
  const create = api.post.create.useMutation({
    onSuccess: async () => {
      setContent("");
      await posts.refetch();
    },
  });

  const [content, setContent] = useState("");

  return (
    <div>
      <h2 className="text-2xl">创建新的</h2>
      <div>
        <input
          className="border-2 border-gray-300 p-1"
          value={content}
          onChange={(e) => setContent(e.target.value)}
          type="text"
        />
        <button
          className="ml-2 border-2 border-gray-300 p-1"
          onClick={() => {
            create.mutate({
              content,
              authorId: user.user?.username ?? "unknown",
            });
          }}
        >
          提交
        </button>
      </div>
      <h2 className="text-2xl">列表</h2>
      <div
        className="border-2 border-gray-300 p-1"
        style={{ maxHeight: "1000px", overflow: "auto" }}
      >
        {posts.data?.map((post) => <div key={post.id}>{post.content}</div>)}
      </div>
    </div>
  );
};

const NotLoginContent = () => {
  return <h1>Not Login</h1>;
};
